### ISSUE TITLE
Image and Title are not exactly centered.

### ISSUE THREAD

**Issue by hemangshah** [mervynokm/UIButton-ImageAndTitlePositioning#5]
<img width="567" alt="screen shot 2018-02-26 at 12 07 21 pm" src="https://user-images.githubusercontent.com/3313412/36656288-a4e3fed6-1aed-11e8-8471-5fa2cf551d27.png">
Image and Title are not exactly centered.

**This doesn't work:**
```
button.contentHorizontalAlignment = .center
button.contentVerticalAlignment = .center
```

**Comment by mervynokm** [comment]
please try the current release and see if you still experience this
